ci: Run performance and layout checks in RuboCop

diff --git a/.github/workflows/ci-markdown-checks.yml b/.github/workflows/ci-markdown-checks.yml
--- a/.github/workflows/ci-markdown-checks.yml
+++ b/.github/workflows/ci-markdown-checks.yml
@@ -108,6 +108,16 @@ jobs:
           set -e # forces exit code to propagate
           npm run check:source:ruby -- --format github
 
+      - name: "Check all ruby files for layout"
+        run: |
+          set -e # forces exit code to propagate
+          npm run check:format:ruby -- --format github
+
+      - name: "Check all ruby files for performance"
+        run: |
+          set -e # forces exit code to propagate
+          npm run check:performance:ruby -- --format github
+
   yaml-lint-check:
     if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
     name: YAML Lint Check
